version: '2.1'

services:
  vue:
    image: andreimariciuc4.azurecr.io/vue:latest
    build: ../energy_fe
    ports:
      - "80:80"

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=energydb
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"

  demo-be:
    image: andreimariciuc4.azurecr.io/be:latest
    build: .
    restart: always
    ports:
      - "8090:8090"
    environment:
      #- DB_IP=172.22.0.2
      - DB_IP=db
      #      - RABBIT_IP=demo-rabbit
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DBNAME=energydb
    links:
      - db

#docker compose up
#docker compose downb